version: '{build}'
image: Visual Studio 2017
configuration: Release
build_script:
  - dotnet pack /p:Version=%APPVEYOR_BUILD_VERSION% /p:GenerateDocumentationFile=true
artifacts:
  - path: CodeFileSanity/bin/Release/*.nupkg
deploy:
  - provider: Environment
    name: nuget
